testType: eval
image: ghcr.io/kptdev/krm-functions-catalog/render-helm-chart:latest
network: true
args:
  name: minecraft
  repo: https://itzg.github.io/minecraft-server-charts
  version: 3.1.3
  releaseName: test
