# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build.environment]
  GO_VERSION = "1.24.10"
  HUGO_VERSION = "v0.148.2"


