# Copyright 2022 Google LLC
# Modifications Copyright (C) 2025 OpenInfra Foundation Europe.
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and push latest dev images
on:
  push:
    branches:
    - "master"

jobs:
  build-push-curated:
    name: Build and push latest curated images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24.3'
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - name: Log in to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push latest and github-ref images
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        make push-curated TAG=latest,$SHORT_SHA DEFAULT_CR=ghcr.io/${{ github.repository }}
  build-push-contrib:
    name: Build and push latest contrib images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24.3'
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - name: Log in to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push latest and github-ref images
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        make push-contrib TAG=latest,$SHORT_SHA DEFAULT_CONTRIB_CR=ghcr.io/${{ github.repository }}/krm-fn-contrib
